//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class NotifyAppenderSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static NotifyAppenderSettings defaultInstance = ((NotifyAppenderSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NotifyAppenderSettings())));
        
        public static NotifyAppenderSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDebugEnabled {
            get {
                return ((bool)(this["IsDebugEnabled"]));
            }
            set {
                this["IsDebugEnabled"] = value;
            }
        }
    }
}
