//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinScpApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class SessionConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static SessionConfig defaultInstance = ((SessionConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SessionConfig())));
        
        public static SessionConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\\\..\\\\history.xml")]
        public string HistoryFilePath {
            get {
                return ((string)(this["HistoryFilePath"]));
            }
            set {
                this["HistoryFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int WatchPeriod {
            get {
                return ((int)(this["WatchPeriod"]));
            }
            set {
                this["WatchPeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int NumberOfSlots {
            get {
                return ((int)(this["NumberOfSlots"]));
            }
            set {
                this["NumberOfSlots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ssh-rsa 2048 13:bd:c2:98:f6:9d:53:f7:1a:6a:38:9d:14:2e:1f:7a")]
        public string SshHostKeyFingerprint {
            get {
                return ((string)(this["SshHostKeyFingerprint"]));
            }
            set {
                this["SshHostKeyFingerprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mole.seedhost.eu")]
        public string Host {
            get {
                return ((string)(this["Host"]));
            }
            set {
                this["Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteSource {
            get {
                return ((bool)(this["DeleteSource"]));
            }
            set {
                this["DeleteSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
        <?xml version=""1.0"" encoding=""utf-16""?>
        <ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
        <string>/home6/emptycup/downloads/completed/test</string>
        <string>/home6/emptycup/downloads/test2</string>
        <string>/home6/emptycup/downloads/completed</string>
        </ArrayOfString>
      ")]
        public global::System.Collections.Specialized.StringCollection RemoteRoots {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RemoteRoots"]));
            }
            set {
                this["RemoteRoots"] = value;
            }
        }
    }
}
