//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("0.1.0.666")]
[assembly: AssemblyFileVersion("0.1.0.666")]
[assembly: AssemblyInformationalVersion("0.1.0.666.62-g2a55586-dirty!-feature/cleanup")]
[assembly: AssemblyCopyright("Copyright (c) mkramers 2017 - 2018")]

